# \ を使用する場合は、必ず\\にしてください.
applicable:
  - ".*[なナﾅ][のノﾉ][\\x{002D}\\x{00AD}\\x{2010}\\x{2011}\\x{2012}\\x{2013}\\x{2014}\\x{2015}\\x{2043}\\x{2212}~～ー=].*"
  - ".*㌨[\\x{002D}\\x{00AD}\\x{2010}\\x{2011}\\x{2012}\\x{2013}\\x{2014}\\x{2015}\\x{2043}\\x{2212}~～ー=].*"
  - ".*㌨.*"
  - ".*<:nano:1017766944180551690>.*"


not_applicable:
  - ".*[なナﾅ][のノﾉ][だダﾀﾞ].*"
  - ".*㌨[だダﾀﾞ].*"
  - ".*[なナﾅ][のノﾉ]族.*"
  - ".*㌨[?？].*"
  - ".*[なナﾅ][のノﾉ][?？].*"

ramen:
  - ".*[らラﾗ]+[あアぁァｱｧ]+[めメﾒ]+[えエぇェｴｪ]+[んンﾝ]+.*"
  - ".*[らラﾗ]+[\\x{002D}\\x{00AD}\\x{2010}\\x{2011}\\x{2012}\\x{2013}\\x{2014}\\x{2015}\\x{2043}\\x{2212}~～ー=]+[めメﾒ]+[\\x{002D}\\x{00AD}\\x{2010}\\x{2011}\\x{2012}\\x{2013}\\x{2014}\\x{2015}\\x{2043}\\x{2212}~～ー=]*[んンﾝ]+.*"

eath_quake_infomation_id:
  - "966138465198702596"

construction_opposition:
  - ".*<:kensetsuhantai:1056538859124564031>.*"
  - ".*<:kensetuhantai:1048575164264218644>.*"

tange:
  - ".*[たタﾀ]+[んンﾝ]+[げゲｹﾞ]+[こコｺ]+[とトﾄ]+[えエｴ]+.*"
  - ".*丹下琴絵.*"